<?xml version="1.0" encoding="utf-8"?><Database Name="dien_may" Class="DBSTDMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=teedeedayne\SQLEXPRESS;Initial Catalog=dien_may;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DLL.Properties.Settings" SettingsPropertyName="dien_mayConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bao_hanh" Member="bao_hanhs">
    <Type Name="bao_hanh">
      <Column Name="ma_bao_hanh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_khach_hang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="nhan_vien_bao_hanh" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ly_do" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngay_gui" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ngay_xong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hoan_thanh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="khach_hang_bao_hanh" Member="khach_hang" ThisKey="ma_khach_hang" OtherKey="ma_khach_hang" Type="khach_hang" IsForeignKey="true" />
      <Association Name="san_pham_bao_hanh" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cap_bac_nhan_vien" Member="cap_bac_nhan_viens">
    <Type Name="cap_bac_nhan_vien">
      <Column Name="ma_cap_bac" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_cap_bac" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="mo_ta_cap_bac" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="cap_bac_nhan_vien_nhan_vien" Member="nhan_viens" ThisKey="ma_cap_bac" OtherKey="ma_cap_bac" Type="nhan_vien" />
    </Type>
  </Table>
  <Table Name="dbo.chi_nhanh" Member="chi_nhanhs">
    <Type Name="chi_nhanh">
      <Column Name="ma_chi_nhanh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_chi_nhanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="khu_vuc" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="chi_nhanh_nhan_vien" Member="nhan_viens" ThisKey="ma_chi_nhanh" OtherKey="ma_chi_nhanh" Type="nhan_vien" />
      <Association Name="chi_nhanh_phieu_xuat_kho" Member="phieu_xuat_khos" ThisKey="ma_chi_nhanh" OtherKey="ma_chi_nhanh_nhap" Type="phieu_xuat_kho" />
      <Association Name="chi_nhanh_san_pham_trong_chi_nhanh" Member="san_pham_trong_chi_nhanhs" ThisKey="ma_chi_nhanh" OtherKey="ma_chi_nhanh" Type="san_pham_trong_chi_nhanh" />
      <Association Name="khu_vuc_chi_nhanh" Member="khu_vuc1" ThisKey="khu_vuc" OtherKey="ma_khu_vuc" Type="khu_vuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chi_tiet_hoa_don" Member="chi_tiet_hoa_dons">
    <Type Name="chi_tiet_hoa_don">
      <Column Name="ma_hoa_don" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_khuyen_mai" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_gio_in" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="hoa_don_chi_tiet_hoa_don" Member="hoa_don" ThisKey="ma_hoa_don" OtherKey="ma_hoa_don" Type="hoa_don" IsForeignKey="true" />
      <Association Name="khuyen_mai_chi_tiet_hoa_don" Member="khuyen_mai" ThisKey="ma_khuyen_mai" OtherKey="ma_khuyen_mai" Type="khuyen_mai" IsForeignKey="true" />
      <Association Name="san_pham_chi_tiet_hoa_don" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.diem_danh" Member="diem_danhs">
    <Type Name="diem_danh">
      <Column Name="ma_diem_danh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="thoi_gian_vao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thoi_gian_ra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nhan_vien_diem_danh" Member="nhan_vien" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hoa_don" Member="hoa_dons">
    <Type Name="hoa_don">
      <Column Name="ma_hoa_don" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien_lap" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_khach_hang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ngay_lap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="hoa_don_chi_tiet_hoa_don" Member="chi_tiet_hoa_dons" ThisKey="ma_hoa_don" OtherKey="ma_hoa_don" Type="chi_tiet_hoa_don" />
      <Association Name="khach_hang_hoa_don" Member="khach_hang" ThisKey="ma_khach_hang" OtherKey="ma_khach_hang" Type="khach_hang" IsForeignKey="true" />
      <Association Name="nhan_vien_hoa_don" Member="nhan_vien" ThisKey="ma_nhan_vien_lap" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khach_hang" Member="khach_hangs">
    <Type Name="khach_hang">
      <Column Name="ma_khach_hang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ho_ten_khach_hang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="xep_hang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="diem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="khach_hang_bao_hanh" Member="bao_hanhs" ThisKey="ma_khach_hang" OtherKey="ma_khach_hang" Type="bao_hanh" />
      <Association Name="khach_hang_hoa_don" Member="hoa_dons" ThisKey="ma_khach_hang" OtherKey="ma_khach_hang" Type="hoa_don" />
      <Association Name="xep_hang_khach_hang" Member="xep_hang1" ThisKey="xep_hang" OtherKey="ma_hang" Type="xep_hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.kho_tong" Member="kho_tongs">
    <Type Name="kho_tong">
      <Column Name="ma_kho" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nhan_vien_quan_ly" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ten_kho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="suc_chua" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="kho_tong_phieu_nhap_kho" Member="phieu_nhap_khos" ThisKey="ma_kho" OtherKey="ma_kho" Type="phieu_nhap_kho" />
      <Association Name="kho_tong_phieu_xuat_kho" Member="phieu_xuat_khos" ThisKey="ma_kho" OtherKey="ma_kho" Type="phieu_xuat_kho" />
      <Association Name="kho_tong_san_pham_trong_kho_tong" Member="san_pham_trong_kho_tongs" ThisKey="ma_kho" OtherKey="ma_kho" Type="san_pham_trong_kho_tong" />
      <Association Name="nhan_vien_kho_tong" Member="nhan_vien" ThisKey="nhan_vien_quan_ly" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khu_vuc" Member="khu_vucs">
    <Type Name="khu_vuc">
      <Column Name="ma_khu_vuc" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_khu_vuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nhan_vien_quan_ly" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="khu_vuc_chi_nhanh" Member="chi_nhanhs" ThisKey="ma_khu_vuc" OtherKey="khu_vuc" Type="chi_nhanh" />
      <Association Name="nhan_vien_khu_vuc" Member="nhan_vien" ThisKey="nhan_vien_quan_ly" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khuyen_mai" Member="khuyen_mais">
    <Type Name="khuyen_mai">
      <Column Name="ma_khuyen_mai" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="giam_gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ma_loai_hang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ngay_bat_dau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ngay_ket_thuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="khuyen_mai_chi_tiet_hoa_don" Member="chi_tiet_hoa_dons" ThisKey="ma_khuyen_mai" OtherKey="ma_khuyen_mai" Type="chi_tiet_hoa_don" />
      <Association Name="loai_hang_khuyen_mai" Member="loai_hang" ThisKey="ma_loai_hang" OtherKey="ma_loai_hang" Type="loai_hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loai_hang" Member="loai_hangs">
    <Type Name="loai_hang">
      <Column Name="ma_loai_hang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_loai_hang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mo_ta" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="loai_hang_khuyen_mai" Member="khuyen_mais" ThisKey="ma_loai_hang" OtherKey="ma_loai_hang" Type="khuyen_mai" />
      <Association Name="loai_hang_san_pham_loai_hang" Member="san_pham_loai_hangs" ThisKey="ma_loai_hang" OtherKey="ma_loai_hang" Type="san_pham_loai_hang" />
    </Type>
  </Table>
  <Table Name="dbo.loai_thuong" Member="loai_thuongs">
    <Type Name="loai_thuong">
      <Column Name="ma_loai_thuong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loai_yeu_cau" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="yeu_cau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="muc_thuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="loai_thuong_thuong" Member="thuongs" ThisKey="ma_loai_thuong" OtherKey="ma_loai_thuong" Type="thuong" />
    </Type>
  </Table>
  <Table Name="dbo.loai_vi_pham" Member="loai_vi_phams">
    <Type Name="loai_vi_pham">
      <Column Name="ma_loai_vi_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mo_ta_vi_pham" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="muc_do_vi_pham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="muc_phat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="loai_vi_pham_vi_pham" Member="vi_phams" ThisKey="ma_loai_vi_pham" OtherKey="ma_loai_vi_pham" Type="vi_pham" />
    </Type>
  </Table>
  <Table Name="dbo.luong" Member="luongs">
    <Type Name="luong">
      <Column Name="ma_phieu_luong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="luong_co_ban" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="he_so" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="thang_luong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="thuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="nhan_vien_luong" Member="nhan_vien" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nghi_viec" Member="nghi_viecs">
    <Type Name="nghi_viec">
      <Column Name="ma_nghi_viec" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nhan_vien_nghi_viec" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ly_do" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="thoi_gian_cho_nghi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="nhan_vien_nghi_viec" Member="nhan_vien" ThisKey="nhan_vien_nghi_viec" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nha_cung_cap" Member="nha_cung_caps">
    <Type Name="nha_cung_cap">
      <Column Name="ma_nha_cung_cap" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_nha_cung_cap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dia_chi_nha_cung_cap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="nha_cung_cap_san_pham" Member="san_phams" ThisKey="ma_nha_cung_cap" OtherKey="ma_nha_cung_cap" Type="san_pham" />
    </Type>
  </Table>
  <Table Name="dbo.nha_san_xuat" Member="nha_san_xuats">
    <Type Name="nha_san_xuat">
      <Column Name="ma_nha_san_xuat" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_nha_san_xuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dia_chi_nha_san_xuat" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="nha_san_xuat_san_pham" Member="san_phams" ThisKey="ma_nha_san_xuat" OtherKey="ma_nha_san_xuat" Type="san_pham" />
    </Type>
  </Table>
  <Table Name="dbo.nhan_vien" Member="nhan_viens">
    <Type Name="nhan_vien">
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ho_va_ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ma_cap_bac" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="so_dien_thoai" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="dia_chi_thuong_tru" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ma_chi_nhanh" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="nhan_vien_diem_danh" Member="diem_danhs" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="diem_danh" />
      <Association Name="nhan_vien_hoa_don" Member="hoa_dons" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien_lap" Type="hoa_don" />
      <Association Name="nhan_vien_kho_tong" Member="kho_tongs" ThisKey="ma_nhan_vien" OtherKey="nhan_vien_quan_ly" Type="kho_tong" />
      <Association Name="nhan_vien_khu_vuc" Member="khu_vucs" ThisKey="ma_nhan_vien" OtherKey="nhan_vien_quan_ly" Type="khu_vuc" />
      <Association Name="nhan_vien_luong" Member="luongs" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="luong" />
      <Association Name="nhan_vien_nghi_viec" Member="nghi_viecs" ThisKey="ma_nhan_vien" OtherKey="nhan_vien_nghi_viec" Type="nghi_viec" />
      <Association Name="nhan_vien_phieu_nhap_kho" Member="phieu_nhap_khos" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien_kiem_tra" Type="phieu_nhap_kho" />
      <Association Name="nhan_vien_phieu_xuat_kho" Member="phieu_xuat_khos" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien_kiem_tra" Type="phieu_xuat_kho" />
      <Association Name="nhan_vien_tai_khoan" Member="tai_khoan" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="tai_khoan" Cardinality="One" />
      <Association Name="nhan_vien_thuong" Member="thuongs" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="thuong" />
      <Association Name="nhan_vien_vi_pham" Member="vi_phams" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="vi_pham" />
      <Association Name="cap_bac_nhan_vien_nhan_vien" Member="cap_bac_nhan_vien" ThisKey="ma_cap_bac" OtherKey="ma_cap_bac" Type="cap_bac_nhan_vien" IsForeignKey="true" />
      <Association Name="chi_nhanh_nhan_vien" Member="chi_nhanh" ThisKey="ma_chi_nhanh" OtherKey="ma_chi_nhanh" Type="chi_nhanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.phieu_nhap_kho" Member="phieu_nhap_khos">
    <Type Name="phieu_nhap_kho">
      <Column Name="ma_phieu_nhap" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_kho" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_nhan_vien_kiem_tra" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="don_gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="kho_tong_phieu_nhap_kho" Member="kho_tong" ThisKey="ma_kho" OtherKey="ma_kho" Type="kho_tong" IsForeignKey="true" />
      <Association Name="nhan_vien_phieu_nhap_kho" Member="nhan_vien" ThisKey="ma_nhan_vien_kiem_tra" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
      <Association Name="san_pham_phieu_nhap_kho" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.phieu_xuat_kho" Member="phieu_xuat_khos">
    <Type Name="phieu_xuat_kho">
      <Column Name="ma_phieu_xuat" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_kho" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_chi_nhanh_nhap" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_nhan_vien_kiem_tra" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="chi_nhanh_phieu_xuat_kho" Member="chi_nhanh" ThisKey="ma_chi_nhanh_nhap" OtherKey="ma_chi_nhanh" Type="chi_nhanh" IsForeignKey="true" />
      <Association Name="kho_tong_phieu_xuat_kho" Member="kho_tong" ThisKey="ma_kho" OtherKey="ma_kho" Type="kho_tong" IsForeignKey="true" />
      <Association Name="nhan_vien_phieu_xuat_kho" Member="nhan_vien" ThisKey="ma_nhan_vien_kiem_tra" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
      <Association Name="san_pham_phieu_xuat_kho" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.san_pham" Member="san_phams">
    <Type Name="san_pham">
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_san_pham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ma_nha_san_xuat" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_nha_cung_cap" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="khoi_luong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="gia_tien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ngay_san_xuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="san_pham_bao_hanh" Member="bao_hanhs" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="bao_hanh" />
      <Association Name="san_pham_chi_tiet_hoa_don" Member="chi_tiet_hoa_dons" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="chi_tiet_hoa_don" />
      <Association Name="san_pham_phieu_nhap_kho" Member="phieu_nhap_khos" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="phieu_nhap_kho" />
      <Association Name="san_pham_phieu_xuat_kho" Member="phieu_xuat_khos" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="phieu_xuat_kho" />
      <Association Name="san_pham_san_pham_loai_hang" Member="san_pham_loai_hangs" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham_loai_hang" />
      <Association Name="san_pham_san_pham_trong_chi_nhanh" Member="san_pham_trong_chi_nhanhs" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham_trong_chi_nhanh" />
      <Association Name="san_pham_san_pham_trong_kho_tong" Member="san_pham_trong_kho_tongs" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham_trong_kho_tong" />
      <Association Name="nha_cung_cap_san_pham" Member="nha_cung_cap" ThisKey="ma_nha_cung_cap" OtherKey="ma_nha_cung_cap" Type="nha_cung_cap" IsForeignKey="true" />
      <Association Name="nha_san_xuat_san_pham" Member="nha_san_xuat" ThisKey="ma_nha_san_xuat" OtherKey="ma_nha_san_xuat" Type="nha_san_xuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.xep_hang" Member="xep_hangs">
    <Type Name="xep_hang">
      <Column Name="ma_hang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_hang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="yeu_cau" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="uu_dai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="xep_hang_khach_hang" Member="khach_hangs" ThisKey="ma_hang" OtherKey="xep_hang" Type="khach_hang" />
    </Type>
  </Table>
  <Table Name="dbo.san_pham_loai_hang" Member="san_pham_loai_hangs">
    <Type Name="san_pham_loai_hang">
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_loai_hang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="loai_hang_san_pham_loai_hang" Member="loai_hang" ThisKey="ma_loai_hang" OtherKey="ma_loai_hang" Type="loai_hang" IsForeignKey="true" />
      <Association Name="san_pham_san_pham_loai_hang" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.san_pham_trong_chi_nhanh" Member="san_pham_trong_chi_nhanhs">
    <Type Name="san_pham_trong_chi_nhanh">
      <Column Name="ma_chi_nhanh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="chi_nhanh_san_pham_trong_chi_nhanh" Member="chi_nhanh" ThisKey="ma_chi_nhanh" OtherKey="ma_chi_nhanh" Type="chi_nhanh" IsForeignKey="true" />
      <Association Name="san_pham_san_pham_trong_chi_nhanh" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.san_pham_trong_kho_tong" Member="san_pham_trong_kho_tongs">
    <Type Name="san_pham_trong_kho_tong">
      <Column Name="ma_kho" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_san_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="kho_tong_san_pham_trong_kho_tong" Member="kho_tong" ThisKey="ma_kho" OtherKey="ma_kho" Type="kho_tong" IsForeignKey="true" />
      <Association Name="san_pham_san_pham_trong_kho_tong" Member="san_pham" ThisKey="ma_san_pham" OtherKey="ma_san_pham" Type="san_pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tai_khoan" Member="tai_khoans">
    <Type Name="tai_khoan">
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mat_khau" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="quyen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="nhan_vien_tai_khoan" Member="nhan_vien" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thuong" Member="thuongs">
    <Type Name="thuong">
      <Column Name="ma_thuong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_loai_thuong" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="thoi_gian_thuong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="loai_thuong_thuong" Member="loai_thuong" ThisKey="ma_loai_thuong" OtherKey="ma_loai_thuong" Type="loai_thuong" IsForeignKey="true" />
      <Association Name="nhan_vien_thuong" Member="nhan_vien" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vi_pham" Member="vi_phams">
    <Type Name="vi_pham">
      <Column Name="ma_vi_pham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ma_nhan_vien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ma_loai_vi_pham" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="thoi_gian_vi_pham" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="loai_vi_pham_vi_pham" Member="loai_vi_pham" ThisKey="ma_loai_vi_pham" OtherKey="ma_loai_vi_pham" Type="loai_vi_pham" IsForeignKey="true" />
      <Association Name="nhan_vien_vi_pham" Member="nhan_vien" ThisKey="ma_nhan_vien" OtherKey="ma_nhan_vien" Type="nhan_vien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>